import type {Metadata} from "next";
import Converter from "@/components/Converter";
import Link from "next/link";
import {site} from "@/lib/site";

export const metadata:Metadata={title:"Free MP3 & WAV Audio Converter – Convert Files Online",description:"Convert your own audio and video files to MP3 or WAV in your browser. Choose audio quality, process files on-device, and download the converted file.",alternates:{canonical:"/"}};

const faqs=[
 ["What is AudioSnap?","AudioSnap is a browser-based audio conversion tool. It can convert supported audio or video files that you own or have permission to process into MP3 or WAV."],
 ["Are my files uploaded to a server?","The local file converter is designed to process selected files in your browser. This keeps the conversion workflow on your device rather than sending the media file to our conversion server."],
 ["Which MP3 quality options are available?","You can choose 128, 192, 256 or 320 kbps for MP3 output. Higher bitrates can produce larger files, while lower bitrates generally create smaller downloads."],
 ["Can I convert video to MP3?","Yes. For supported local video formats, AudioSnap can extract the audio track and encode it as MP3 in your browser."],
 ["Can I use AudioSnap on mobile?","The interface is responsive and can be used in modern mobile browsers. Large files may take longer on devices with less memory or processing power."],
 ["Why can a conversion fail?","A file may use an unsupported codec, be too large for the available browser memory, be damaged, or the browser may not support the required processing features."],
 ["Is YouTube URL conversion available?","Direct YouTube URL conversion is currently unavailable. The working converter is for local files you own or are authorized to process."],
 ["Is AudioSnap free?","The browser file conversion interface is available without a paid account."],
 ["Do I need to install software?","No desktop installation is required. The conversion engine runs through the website in a compatible browser."],
 ["What content can I convert?","Only convert content you created, own, have permission to use, or are otherwise authorized to process. Do not use the service to bypass access controls or other restrictions."]
];

export default function Home(){
 const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};
 return <main>
  <section className="hero"><div className="container"><span className="eyebrow">Private • Browser Based • Mobile Friendly</span><h1>Free MP3 & WAV Audio Converter</h1><p>Convert audio and video files you own or have permission to process into MP3 or WAV. Choose your audio quality and process supported files directly in your browser.</p><Converter/></div></section>
  <section className="section"><div className="container"><h2>A simple online audio converter</h2><p className="section-intro">AudioSnap is built for people who need a straightforward way to change an audio or video file into a useful audio format. Instead of complicated desktop software, the converter provides a clean workflow in a modern web browser.</p><div className="grid">{[["Browser-Based Processing","Your selected local file is processed in the browser for a more private conversion workflow."],["MP3 Quality Choices","Choose 128, 192, 256 or 320 kbps depending on the balance you want between file size and bitrate."],["Video to Audio","Extract the audio track from supported video files and save it as MP3 or WAV."],["Mobile Friendly","The responsive interface is designed for phones, tablets, laptops and desktop computers."],["No Account Required","Use the local converter without creating an account or completing a complicated setup."],["Clear Download Flow","Follow conversion progress and download the finished audio file when processing completes."]].map(([h,p])=><div className="card" key={h}><h3>{h}</h3><p>{p}</p></div>)}</div></div></section>
  <section className="section white"><div className="container content">
   <h2>How to convert a video or audio file to MP3</h2><p>Start by selecting <strong>Choose audio/video file</strong> in the converter. Pick a media file that you own or have permission to process. If you are creating an MP3, select a bitrate such as 128, 192, 256 or 320 kbps, then start the conversion. AudioSnap loads its browser processing engine, shows conversion progress, and provides a download button when the output is ready.</p><p>Because media processing can require significant memory, smaller files will normally be easier for a browser to handle than very large or lengthy videos. Processing speed also depends on the device, browser and source format.</p>
   <h2>MP4 to MP3 and video to MP3 conversion</h2><p>Video files often contain an audio stream alongside the picture. A video-to-MP3 converter extracts that audio and encodes it into the MP3 format. This can be useful for your own recordings, presentations, interviews, voice notes, lectures you created, podcasts, or other media you are authorized to repurpose.</p><p>AudioSnap uses a WebAssembly media-processing engine for supported local files. The goal is to provide the convenience of an online tool while keeping local-file processing in the browser.</p>
   <h2>Choosing the right MP3 bitrate</h2><p><strong>128 kbps</strong> creates smaller files and can be suitable for speech. <strong>192 kbps</strong> offers a practical balance for general listening. <strong>256 kbps</strong> provides a higher bitrate when file size is less important, while <strong>320 kbps</strong> is the highest MP3 bitrate offered by the interface. Selecting a higher bitrate does not restore quality that is missing from the original source.</p>
   <h2>MP3 or WAV: which format should you use?</h2><p>MP3 uses lossy compression and is widely supported, making it convenient when you want smaller files for everyday playback. WAV is commonly used when you want uncompressed PCM audio for editing or workflows where a larger file is acceptable. You can visit our <Link href="/youtube-to-wav">WAV converter</Link> page when WAV output is more suitable.</p>
   <h2>Private browser-based file processing</h2><p>For the local converter, the selected media is processed on your device rather than being sent to our conversion API. This approach can improve privacy, although the browser still needs to load the conversion engine required to perform the task. As with any web tool, avoid selecting sensitive material on a device or network you do not trust.</p>
   <h2>Using the converter responsibly</h2><p>Audio conversion technology has many legitimate uses, but you should only process media that you created, own, have permission to use, or are otherwise legally authorized to convert. AudioSnap is not designed to bypass DRM, authentication, paywalls or access controls. Direct YouTube URL conversion is currently unavailable; use the working local converter for authorized files.</p>
   <h2>Common conversion problems</h2><p>If a file does not convert, try a smaller supported media file and keep the browser tab open while processing. Very large files can exceed the memory available to a browser, especially on mobile devices. A damaged source file or an unusual codec can also prevent successful decoding.</p>
   <h2>Why use an online audio converter?</h2><p>A browser converter can be convenient when you do not want to install a full desktop editing application for a simple format change. AudioSnap focuses on the essential steps: select a file, choose an output option, monitor progress and download the result. For more details, see <Link href="/how-it-works">how AudioSnap works</Link> or review the <Link href="/faq">complete FAQ</Link>.</p>
   <h2>Frequently asked questions</h2>{faqs.map(([q,a])=><div key={q}><h3>{q}</h3><p>{a}</p></div>)}<p><Link className="button" href="/faq">View all FAQs</Link></p>
  </div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/>
 </main>
}
