"use client";
import {useRef,useState} from "react";
import type {FFmpeg as FFmpegType} from "@ffmpeg/ffmpeg";

export default function Converter({format="mp3"}:{format?:"mp3"|"wav"}){
 const[quality,setQuality]=useState("192"); const[message,setMessage]=useState(""); const[loading,setLoading]=useState(false); const[file,setFile]=useState<File|null>(null); const[progress,setProgress]=useState(0); const[downloadUrl,setDownloadUrl]=useState(""); const fileRef=useRef<HTMLInputElement>(null); const ffmpegRef=useRef<FFmpegType|null>(null);
 async function convertLocal(){if(!file){fileRef.current?.click();return}setLoading(true);setProgress(0);setMessage("Loading secure browser converter…");if(downloadUrl){URL.revokeObjectURL(downloadUrl);setDownloadUrl("")}try{const [{FFmpeg},{fetchFile,toBlobURL}]=await Promise.all([import("@ffmpeg/ffmpeg"),import("@ffmpeg/util")]);let ffmpeg=ffmpegRef.current;if(!ffmpeg){ffmpeg=new FFmpeg();ffmpeg.on("progress",({progress})=>setProgress(Math.max(0,Math.min(100,Math.round(progress*100)))));const base="https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/umd";await ffmpeg.load({coreURL:await toBlobURL(`${base}/ffmpeg-core.js`,"text/javascript"),wasmURL:await toBlobURL(`${base}/ffmpeg-core.wasm`,"application/wasm")});ffmpegRef.current=ffmpeg}setMessage("Converting on your device…");const ext=file.name.split(".").pop()?.replace(/[^a-zA-Z0-9]/g,"")||"input";const input=`input.${ext}`;const output=format==="wav"?"audiosnap-output.wav":"audiosnap-output.mp3";await ffmpeg.writeFile(input,await fetchFile(file));const args=format==="wav"?["-i",input,"-vn","-c:a","pcm_s16le",output]:["-i",input,"-vn","-c:a","libmp3lame","-b:a",`${quality}k`,output];await ffmpeg.exec(args);const data=await ffmpeg.readFile(output);const bytes=data instanceof Uint8Array?data:new TextEncoder().encode(data);const blob=new Blob([bytes as BlobPart],{type:format==="wav"?"audio/wav":"audio/mpeg"});const objectUrl=URL.createObjectURL(blob);setDownloadUrl(objectUrl);setProgress(100);setMessage("Conversion complete. Your download is ready.");await ffmpeg.deleteFile(input);await ffmpeg.deleteFile(output)}catch(e:any){console.error(e);setMessage("Conversion could not be completed in this browser. Try a smaller MP4, WebM, M4A, WAV or MP3 file.")}finally{setLoading(false)}}
 const safeBase=(file?.name||"audiosnap-audio").replace(/\.[^.]+$/,"").replace(/[^a-zA-Z0-9-_ ]/g,"").trim()||"audiosnap-audio";
 return <div id="converter" className="converter-card">
  <div className="url-disabled"><div className="status-row"><strong>YouTube URL conversion</strong><span className="coming-badge">Coming soon</span></div><p>This option is temporarily unavailable. Please use the secure file converter below.</p><input value="" placeholder="YouTube URL conversion is not available yet" disabled/><button type="button" className="button wide" disabled>Convert from YouTube</button></div>
  <div className="divider"><span>AVAILABLE NOW</span></div>
  <div className="local-converter"><h3>Convert your own file</h3><p>Choose a video or audio file you own or have permission to convert. Processing happens in your browser.</p>{format==="mp3"&&<div className="local-quality"><label>MP3 quality</label><select value={quality} onChange={e=>setQuality(e.target.value)} disabled={loading}><option value="128">128 kbps</option><option value="192">192 kbps</option><option value="256">256 kbps</option><option value="320">320 kbps</option></select></div>}<input ref={fileRef} className="file-input" type="file" accept="audio/*,video/*" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);setProgress(0);setMessage(f?`Selected: ${f.name}`:"");if(downloadUrl){URL.revokeObjectURL(downloadUrl);setDownloadUrl("")}}}/><button type="button" className="ghost wide-ghost" disabled={loading} onClick={()=>fileRef.current?.click()}>{file?`Change file: ${file.name}`:"Choose audio/video file"}</button>{file&&<button type="button" className="button wide" disabled={loading} onClick={convertLocal}>{loading?`Converting… ${progress}%`:`Convert file to ${format.toUpperCase()}`}</button>}{loading&&<div className="progress-track"><div className="progress-fill" style={{width:`${progress}%`}}/></div>}{downloadUrl&&<a className="download-button" href={downloadUrl} download={`${safeBase}.${format}`}>Download {format.toUpperCase()}</a>}</div>
  {message&&<div className="alert">{message}</div>}<p className="notice">Use this tool only with content you own or are authorized to convert.</p>
 </div>
}
