"use client";
import {useRef,useState} from "react";
import type {FFmpeg as FFmpegType} from "@ffmpeg/ffmpeg";

type Preview={title:string;author:string;thumbnail:string;url:string};
const MAX_FILE_SIZE=200*1024*1024;
const MP3_QUALITIES=["320","256","192","128"];

export default function Converter({format="mp3"}:{format?:"mp3"|"wav"}){
 const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);const[file,setFile]=useState<File|null>(null);const[url,setUrl]=useState("");const[preview,setPreview]=useState<Preview|null>(null);const[progress,setProgress]=useState(0);const[downloadUrl,setDownloadUrl]=useState("");const[downloadName,setDownloadName]=useState("audiosnap-audio");const[activeQuality,setActiveQuality]=useState("");const[readyQuality,setReadyQuality]=useState("");const[showDownloadModal,setShowDownloadModal]=useState(false);
 const fileRef=useRef<HTMLInputElement>(null);const ffmpegRef=useRef<FFmpegType|null>(null);
 function clearDownload(){if(downloadUrl)URL.revokeObjectURL(downloadUrl);setDownloadUrl("");setReadyQuality("");setShowDownloadModal(false)}
 async function getFFmpeg(){const[{FFmpeg},{toBlobURL}]=await Promise.all([import("@ffmpeg/ffmpeg"),import("@ffmpeg/util")]);let ffmpeg=ffmpegRef.current;if(!ffmpeg){ffmpeg=new FFmpeg();ffmpeg.on("progress",({progress})=>setProgress(Math.max(0,Math.min(100,Math.round(progress*100)))));const base="https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/umd";await ffmpeg.load({coreURL:await toBlobURL(`${base}/ffmpeg-core.js`,"text/javascript"),wasmURL:await toBlobURL(`${base}/ffmpeg-core.wasm`,"application/wasm")});ffmpegRef.current=ffmpeg}return ffmpeg}
 async function convertSource(source:File,name:string,bitrate="192"){setLoading(true);setActiveQuality(bitrate);setProgress(0);clearDownload();try{if(source.size>MAX_FILE_SIZE)throw new Error("File is too large. Please use a file under 200 MB.");setMessage("Loading secure browser converter…");const[{fetchFile},ffmpeg]=await Promise.all([import("@ffmpeg/util"),getFFmpeg()]);setMessage(`Converting to ${format.toUpperCase()}${format==="mp3"?` at ${bitrate} kbps`:""}…`);const ext=source.name.split(".").pop()?.replace(/[^a-zA-Z0-9]/g,"")||"media";const input=`input.${ext}`;const output=format==="wav"?"audiosnap-output.wav":"audiosnap-output.mp3";await ffmpeg.writeFile(input,await fetchFile(source));const args=format==="wav"?["-i",input,"-vn","-c:a","pcm_s16le",output]:["-i",input,"-vn","-c:a","libmp3lame","-b:a",`${bitrate}k`,output];await ffmpeg.exec(args);const data=await ffmpeg.readFile(output);const bytes=data instanceof Uint8Array?data:new TextEncoder().encode(data);const blob=new Blob([bytes as BlobPart],{type:format==="wav"?"audio/wav":"audio/mpeg"});setDownloadUrl(URL.createObjectURL(blob));setDownloadName(name.replace(/\.[^.]+$/,"").replace(/[^a-zA-Z0-9-_ ]/g,"").trim()||"audiosnap-audio");setReadyQuality(bitrate);setProgress(100);setMessage("Conversion complete. Click Download to continue.");await ffmpeg.deleteFile(input);await ffmpeg.deleteFile(output)}catch(e:any){console.error(e);setMessage(e?.message||"Conversion could not be completed. Try another supported media file.")}finally{setLoading(false);setActiveQuality("")}}
 async function checkYouTube(e:React.FormEvent){e.preventDefault();setLoading(true);setPreview(null);setFile(null);setMessage("Checking YouTube video…");clearDownload();try{const r=await fetch("/api/youtube-preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Could not load video.");setPreview(data);setMessage("Video found. Select your own or authorized copy below to convert it.")}catch(e:any){setMessage(e?.message||"Could not load the YouTube video.")}finally{setLoading(false)}}
 function chooseFile(){fileRef.current?.click()}
 async function handleQuality(q:string){if(!file){setMessage("Select your own or authorized copy of this video first.");chooseFile();return}await convertSource(file,preview?.title||file.name,q)}
 function openDownload(){if(downloadUrl)setShowDownloadModal(true)}
 const finalName=format==="mp3"?`${downloadName}-${readyQuality||"192"}kbps.mp3`:`${downloadName}.wav`;
 return <div id="converter" className="converter-card">
  <form onSubmit={checkYouTube} className="url-converter"><div className="status-row"><strong>YouTube video</strong><span className="live-badge">URL Check</span></div><p>Paste a YouTube URL to load the public title and thumbnail, then use your own or authorized media copy for conversion.</p><label htmlFor="youtube-url">YouTube URL</label><div className="input-row"><input id="youtube-url" value={url} onChange={e=>{setUrl(e.target.value);setPreview(null);clearDownload()}} placeholder="https://www.youtube.com/watch?v=..." type="url" required disabled={loading}/></div><button type="submit" className="button wide" disabled={loading||!url.trim()}>{loading&&!preview?"Checking…":"Check YouTube Video"}</button></form>
  <input ref={fileRef} className="file-input" type="file" accept="audio/*,video/*" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);setProgress(0);clearDownload();setMessage(f?`Selected: ${f.name}`:"")}}/>
  {preview&&<div className="result-panel"><div className="result-media"><img src={preview.thumbnail} alt="YouTube video thumbnail"/><h3>{preview.title}</h3><p>{preview.author}</p><button type="button" className="ghost select-copy" onClick={chooseFile} disabled={loading}>{file?`Selected: ${file.name}`:"Choose authorized media copy"}</button></div><div className="quality-panel"><div className="format-tabs"><span className="format-tab active">♫ Audio</span><span className="format-tab muted">▣ Video</span></div>{format==="mp3"?<div className="quality-table"><div className="quality-head"><span>FILE TYPE</span><span>FORMAT</span><span>ACTION</span></div>{MP3_QUALITIES.map(q=><div className="quality-row" key={q}><strong>{q}kbps</strong><span>mp3</span><span>{downloadUrl&&readyQuality===q?<button className="row-download" type="button" onClick={openDownload}>↓ Download</button>:<button className="row-action" type="button" onClick={()=>handleQuality(q)} disabled={loading}>{loading&&activeQuality===q?`Converting ${progress}%`:file?"Convert":"Select file"}</button>}</span></div>)}</div>:<div className="quality-table"><div className="quality-head"><span>FILE TYPE</span><span>FORMAT</span><span>ACTION</span></div><div className="quality-row"><strong>Lossless</strong><span>wav</span><span>{downloadUrl?<button className="row-download" type="button" onClick={openDownload}>↓ Download</button>:<button className="row-action" type="button" onClick={()=>handleQuality("wav")} disabled={loading}>{loading?`Converting ${progress}%`:file?"Convert":"Select file"}</button>}</span></div></div>}</div></div>}
  {!preview&&<div className="divider"><span>OR CONVERT A LOCAL FILE</span></div>}
  {!preview&&<div className="local-converter"><h3>Convert your own file</h3><p>Choose an audio or video file from your device. Processing happens locally in your browser.</p><button type="button" className="ghost wide-ghost" disabled={loading} onClick={chooseFile}>{file?`Selected: ${file.name}`:"Choose audio/video file"}</button>{file&&<button type="button" className="button wide" disabled={loading} onClick={()=>convertSource(file,file.name,"192")}>{loading?`Converting… ${progress}%`:`Convert to ${format.toUpperCase()}`}</button>}</div>}
  {loading&&progress>0&&<div className="progress-track"><div className="progress-fill" style={{width:`${progress}%`}}/></div>}{message&&<div className="alert">{message}</div>}<p className="notice">YouTube URL checking loads public metadata only. Audio conversion requires a media file you own or are authorized to process.</p>
  {showDownloadModal&&downloadUrl&&<div className="download-modal-backdrop" role="dialog" aria-modal="true"><div className="download-modal"><div className="download-modal-head"><strong>{preview?.title||downloadName}</strong><button type="button" className="modal-close" onClick={()=>setShowDownloadModal(false)} aria-label="Close">×</button></div><div className="download-modal-body"><div className="download-ready-icon">✓</div><h3>Your {format.toUpperCase()} is ready</h3><p>{format==="mp3"?`${readyQuality} kbps MP3`:"WAV audio"} has finished processing.</p><a className="download-now" href={downloadUrl} download={finalName} onClick={()=>setTimeout(()=>setShowDownloadModal(false),400)}>↓ Download Now</a><p className="modal-thanks">Thanks for using AudioSnap.</p></div></div></div>}
 </div>
}
